version: "3.7"

services:
  hcd-mca:
    image: delirium/horcrux-demonstrator:mca
    ports:
      - "1000:1880"
    volumes:
      - ./mca/data:/data

  hcd-issuer:
    image: delirium/horcrux-demonstrator:issuer
    ports: 
      - "1001:1880"
    volumes:
      - ./issuer/data:/data
  
  hcd-identity-hub:
    image: delirium/horcrux-demonstrator:identity-hub
    ports: 
      - "1002:1880"
    volumes:
      - ./identityHub/data:/data

  hcd-bops: 
    image: delirium/horcrux-demonstrator:bops
    ports: 
      - "1003:1880"
    volumes:
      - ./bops/data:/data

  hcd-bchain:
    image: delirium/horcrux-demonstrator:bchain
    ports: 
      - "1004:1880"
    volumes:
      - ./bchain/data:/data

  hcd-verifier:
    image: delirium/horcrux-demonstrator:verifier
    ports:
      - "1005:1880"
    volumes:
      - ./verifier/data:/data
